### ISSUE TITLE
Split up breit wigner lineshape functionality

### ISSUE THREAD

**Issue by spflueger** [apoluekt/AmpliTF#3]
The current `breit_wigner_lineshape` also calculates the barrier factors for the production. In other words it describes the full dynamics amplitude for a 3 body decay.

It would be more convenient to separate out the parts so that `breit_wigner_lineshape` only includes the functionality of one two body decay.

```python
@atfi.function
def breit_wigner_lineshape(
    m2,
    m0,
    gamma0,
    ma,
    mb,
    dr,
    lr,
    barrier_factor=True,
    ma0=None,
):
    """
    Breit-Wigner amplitude with Blatt-Weisskopf formfactors, mass-dependent width and orbital barriers
    """
    m = atfi.sqrt(m2)
    p = atfk.two_body_momentum(m, ma, mb)
    p0 = atfk.two_body_momentum(m0, ma if ma0 is None else ma0, mb)
    ffr = blatt_weisskopf_ff(p, p0, dr, lr)
    width = mass_dependent_width(m, m0, gamma0, p, p0, ffr, lr)
    bw = relativistic_breit_wigner(m2, m0, width)
    ff = ffr
    if barrier_factor:
        ff *= orbital_barrier_factor(p, p0, lr)
    return bw * atfi.complex(ff, atfi.const(0.0))
```

**Comment by apoluekt** [comment]
Good point. I guess this is a use case for scattering experiments? In the meson decays, the production and decay parts always go together. Maybe makes sense to have both versions.

**Comment by spflueger** [comment]
In ComPWA the total reaction is defined in a feynman like diagrams or graph. Every edge is a state and a nodes represent interactions. And each element of the graph has the appropriate properties.
Then the amplitude is just built up by putting the individual terms together correctly. That's why it would be convenient to have a building blocks that only represent a single interaction node.

> In the meson decays, the production and decay parts always go together.

I don't fully understand this. Can you make an example reaction for me? I would have expected that also this process can be split up into a production and decay term.

Having both versions is fine for me (the smaller building blocks can even just be reused there)

**Comment by apoluekt** [comment]
I'm mostly thinking about 3-body decays, D->RC, R->AB. Surely this can be split in two interactions. My point is just it's useful to have a single function for this (very common for us) case, to save some typing.

**Comment by spflueger** [comment]
Oh yeah, of course

**Comment by apoluekt** [comment]
Hi Stefan, I've merged your changes to master. Is this issue closed now? I don't see any changes to Breit-Wigner in your commit, though. Are the changes to BW FFs fix this?

**Comment by spflueger** [comment]
I can make a pull request for that.

Btw, in tensorwaves we currently use [this fork](https://github.com/ComPWA/AmpliTF). We have setup a release workflow there for making the pypi packages. It would be also good to hand this over to you.

**Comment by apoluekt** [comment]
Cool, please make a request to keep the master branch in sync with ComPWA. I plan some cleanup afterwards (remove the fitting and toymc code and move it to a separate python package).

**Comment by spflueger** [comment]
> Cool, please make a request to keep the master branch in sync with ComPWA.

You mean I should include all changes from the ComPWA fork in that PR?

**Comment by apoluekt** [comment]
I don't see many changes by comparing to the master branch. Basically, only q_squared instead of q in BW FF.
