### ISSUE TITLE
Remove toymc and optimisation code

### ISSUE THREAD

**Issue by apoluekt** [apoluekt/AmpliTF#6]
As discussed before, we will keep the functionality of AmpliTF to a bare minimum, implementing only the kinematic and dynamical HEP-related functions and classes, to avoid duplication of functionality with ComPWA and zfit. I'm now going to remove the toymc.py and optimisation.py from AmpliTF and move it to a separate package (TFA2) which will provide the functionality of TensorFlowAnalysis but with TF v2. 

@spflueger I guess this is safe for you, since these functions are not used in ComPWA. Just double checking.

**Comment by spflueger** [comment]
That is correct

**Comment by apoluekt** [comment]
Closing issue, the optimisation and fitting code moved to https://github.com/apoluekt/TFA2
